const MODULE = Object.freeze({
  ADMIN: Object.freeze({
    VOUCHER: 'admin_voucher',
    VOUCHER_HISTORY: 'admin_voucher_history',
    LOYALTY_HISTORY: 'admin_loyalty_history',
  }),
  APP: Object.freeze({
    DRIVER_WORKING_SCHEDULE: 'app_driver_working_schedule',
    FAQS: 'app_faqs',
    LOCATION: 'app_location',
    NOTIFICATION: 'app_notification',
    ORDER: 'app_order',
    ORDER_DELIVERY: 'app_order_delivery',
    ORDER_DELIVERY_STATUSES: 'app_order_delivery_statuses',
    ORDER_ITEM: 'app_order_item',
    ORDER_STATUSES: 'app_order_statuses',
    PAY_FAST_LOGS: 'app_payfast_logs',
    STRIPE_LOGS: 'app_stripe_logs',
    USER: 'app_user',
    USER_ADDRESS: 'app_user_address',
    USER_CART: 'app_user_cart',
    USER_CART_ITEM: 'app_user_cart_item',
    USER_DEVICE: 'app_user_device',
    USER_DRIVER_EXTENSION: 'app_user_driver_ext',
    RATING: 'rating',
  }),
  SHOPTYPE: 'shop_type',
  THEME: 'theme',
  SYSTEM_CONFIG: 'system_config',
  APPOINTMENT: 'appointment',
  WALLETS: 'wallets',
  WALLET_TRANSCATIONS: 'wallet_transactions',
  APPOINTMENT_PROVIDER: 'appointment_provider',
  APPOINTMENT_PROVIDER_SCHEDULE: 'appointment_provider_schedule',
  APPOINTMENT_SERVICE: 'appointment_service',
  AS_PAYMENT_METHODS: 'as_payment_methods',
  BACK_OFFICE_USER: 'backoffice_user',
  BANNER: 'banner',
  HOME_CATEGORY: 'home_category',
  HOME_CATEGORY_ITEM: 'home_cat_item',
  HOME_CATEGORY_ITEM_FAQ: 'home_cat_item_faq',
  NOTIFICATION: 'notification',
  NOTIFICATION_BATCH: 'notification_batch',
  PARAMETER: 'parameter',
  PERMISSION: 'permission',
  REWARDS: 'rewards',
  ROLE: 'role',
  ROLE_PERMISSION: 'role_permission',
  TENANT: 'tenant',
  TENANT_CONFIG: 'tenant_config',
  SHOP_EVENT_HOLIDAYS: 'tenant_event_holidays',
  VIEW: Object.freeze({
    CART_DETAIL: 'cart_detail_view',
    CART_LIST: 'cart_list_view',
    ORDER_DETAIL: 'order_detail_view',
    ORDER_LIST: 'order_list_view',
  }),
  STORE: Object.freeze({
    APPOINTMENT: 'store_appointment',
    EMPLOYEE: 'store_employee',
    EMPLOYEE_SCHEDULE: 'store_employee_schedule',
    EMPLOYEE_RATING: 'store_employee_rating',
    EMPLOYEE_SERVICE: 'store_employee_service',
    EMPLOYEE_ATTENDANCE: 'store_employee_attendance',
    EMPLOYEE_DEVICE: 'store_employee_device',
    EMPLOYEE_PAYROLL: 'store_employee_payroll',
    EMPLOYEE_LEAVE: 'store_employee_leave',
    EMPLOYEE_LEAVE_ATTACHMENT: 'store_employee_leave_attachment',
    SERVICE_CATEGORY: 'store_service_category',
    SERVICE_CATEGORY_ITEM: 'store_service_category_item',
  }),
  NEW_EARTH: Object.freeze({
    PROJECTS: 'ne_projects',
    PRODUCTS: 'ne_products',
    PROJECT_PLANS: 'ne_project_plans',
    PROJECT_ATTACHMENT: 'ne_project_attachments',
    VENDORS: 'ne_vendors',
  }),
  EXPENSE: 'expense',
});

module.exports = MODULE;
