const NOTIFICATION = 'NOTIFICATION';
const EMAIL = 'EMAIL';
const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
const PUSH_NOTIFICATION_BATCH = 'PUSH_NOTIFICATION_BATCH';
const PUSH_NOTIFICATION_BATCH_DELL = 'PUSH_NOTIFICATION_BATCH_DELL';

module.exports = Object.freeze({
  NOTIFICATION,
  EMAIL,
  PUSH_NOTIFICATION,
  PUSH_NOTIFICATION_BATCH,
  PUSH_NOTIFICATION_BATCH_DELL,
});
