function generateNewPhraseEmail(obj) {
  return `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial,sans-serif}@media print{body{font-size:12pt;line-height:1.4;background-color:#fff}}</style></head><body><div style="container-type:inline-size;padding-top:3%;padding-bottom:3%;max-width:450px;margin:auto;text-align:center"><div style="margin-bottom:2%"><img src="${obj.logo}" alt="Asset-1-4x-1"></div><div><img src="${obj.headerImage}" alt="Key"></div><div><p style="color:#1c1f22;font-size:25px;font-style:normal;font-weight:600;line-height:105.023%">${obj.heading}</p></div><div><p style="color:#1c1f22;font-size:12px;font-style:normal;font-weight:400;text-align:center;line-height:156.5%">${obj.message}</p></div><div style="padding-top:1%;padding-bottom:3%"><a href=${obj.link} target="_blank"><button style="cursor:pointer;border:0;outline:0;width:200px;height:40px;flex-shrink:0;background-color:#0096ff"><span style="font-size:12px;color:#fff;font-style:normal;font-weight:400;text-align:center">Reset your password</span></button></a></div><hr style="margin:5%"><div style="margin-top:2%;margin-bottom:5%"><a href="https://www.facebook.com/profile.php?id=61552473566262"><img src="https://lundry-app-admin.s3.ca-central-1.amazonaws.com/app/images/1ac59309-53ad-43ac-9239-dfe7cd5ae967-fb.png" alt="fb"></a> <a href="https://twitter.com/UrAppTech" ><img style="margin-left:5%;margin-right:5%" src="https://lundry-app-admin.s3.ca-central-1.amazonaws.com/app/images/034f0f81-d621-4608-b13a-9bbd02a2fc4b-twitter.png" alt="twitter"></a> <a href="https://www.instagram.com/urapptechnologies/" ><img src="https://lundry-app-admin.s3.ca-central-1.amazonaws.com/app/images/5cc501d3-3c7f-4b45-9a93-5435482e9c59-insta.png" alt="insta"></a></div><div style="text-align:center"><p style="margin:0;color:#1c1f22;font-size:12px;font-style:normal;font-weight:400;text-align:center;line-height:156.5%">Problems or questions? Call us at +980 555 666<br>or email info@example.com</p><span style="color:#1c1f22;font-size:12px;font-style:normal;font-weight:400;text-align:center;line-height:156.5%">2023 URLaundry Ltd. All Rights Reserved</span></div></div></body></html>`;
}

function generateOTPEmail(data) {
  return `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html dir="ltr" lang="en"><head><meta content="text/html; charset=UTF-8" http-equiv=Content-Type><meta name=x-apple-disable-message-reformatting></head><body style="background-color:#fff;margin-top:0;margin-bottom:0;margin-left:auto;margin-right:auto;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif"><div style=display:none;overflow:hidden;line-height:1px;opacity:0;max-height:0;max-width:0>${data.heading}</div><table align=center width=100% border=0 cellpadding=0 cellspacing=0 role=presentation style=max-width:37.5em;margin-top:0;margin-bottom:0;margin-left:auto;margin-right:auto;padding-top:0;padding-bottom:0;padding-left:1.25rem;padding-right:1.25rem><tbody><tr style=width:100%><td><h1 style=color:#1d1c1d;font-size:2.25rem;line-height:2.5rem;font-weight:700;margin-top:2rem;margin-bottom:2rem;margin-left:0;margin-right:0;padding:0>${data.heading}</h1><p style="font-size:1.25rem;line-height:1.75rem;margin:16px 0;margin-bottom:2rem">${data.message}</p><table align=center width=100% border=0 cellpadding=0 cellspacing=0 role=presentation style=background-color:#f5f4f5;border-radius:.25rem;margin-bottom:2rem;padding-top:2.5rem;padding-bottom:2.5rem;padding-left:.625rem;padding-right:.625rem><tbody><tr><td><p style="font-size:1.875rem;line-height:2.25rem;margin:16px 0;vertical-align:middle;text-align:center;letter-spacing:.5rem">${data.code}</p></td></tr></tbody></table><p style="font-size:1.25rem;line-height:1.75rem;margin:16px 0;margin-bottom:2rem;text-align:center;color:#ea580c;font-weight:600">${data.expirationMessage}</p><p style="font-size:.875rem;line-height:1.25rem;margin:16px 0;color:#000">If you didn't request this email, there's nothing to worry about, you can safely ignore it.</p></td></tr></tbody></table></body></html>`;
}

module.exports = { generateNewPhraseEmail, generateOTPEmail };
